on: push
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.7.8+hotfix.4'
    - run: flutter pub get
      working-directory: /Frontend/searchlight_gui/
    - run: flutter test
      working-directory: /Frontend/searchlight_gui/
    - run: flutter build apk --debug --split-per-abi
      working-directory: /Frontend/searchlight_gui/
    - name: Push APK to Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: "Frontend/searchlight_gui/build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.TOKEN }}
