# This is a basic workflow to help you get started with Actions

name: CI Windows Build Zip

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 build:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
     - working-directory: ./Frontend/new_proj_flutter
       run: flutter config --enable-windows-desktop
     - working-directory: ./Frontend/new_proj_flutter
       run: flutter build windows
     - working-directory: ./Frontend/new_proj_flutter/build/windows/
       run: tar.exe -a -c -f out.zip *.*
     
     - name: Upload a Build Artifact
       uses: actions/upload-artifact@v3.1.0
       with:
        name: "*.zip"
        path: ./Frontend/new_proj_flutter/build/windows/
